server {
    listen 8080;
    listen [::]:8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 308 /docs/;
    }

    location = /docs {
        return 308 /docs/;
    }

    location /docs/ {
        try_files $uri $uri/ $uri/index.html /docs/404.html;
    }
}
