#!/usr/bin/env python3
"""Refresh pinned TA-Lib metadata snapshots used by PalmScript tooling.

This script intentionally lives outside the runtime path. It fetches the
repository-pinned upstream metadata and writes raw snapshots into
`vendor/talib/` so CI and local review can diff the exact source inputs.
"""

from __future__ import annotations

import pathlib
import urllib.request
import xml.etree.ElementTree as ET


COMMIT = "1bdf54384036852952b8b4cb97c09359ae407bd0"
FILES = {
    "ta_func_api.xml": f"https://raw.githubusercontent.com/TA-Lib/ta-lib/{COMMIT}/ta_func_api.xml",
    "ta_func_list.txt": f"https://raw.githubusercontent.com/TA-Lib/ta-lib/{COMMIT}/ta_func_list.txt",
    "LICENSE": f"https://raw.githubusercontent.com/TA-Lib/ta-lib/{COMMIT}/LICENSE",
}


def main() -> None:
    root = pathlib.Path(__file__).resolve().parent.parent
    out_dir = root / "vendor" / "talib"
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, url in FILES.items():
        with urllib.request.urlopen(url) as response:
            (out_dir / name).write_bytes(response.read())
    generated = root / "src" / "talib_generated.rs"
    generated.write_text(render_generated_metadata(out_dir / "ta_func_api.xml"))
    print(f"synced {len(FILES)} files from TA-Lib {COMMIT} into {out_dir}")
    print(f"updated generated metadata at {generated}")


def render_generated_metadata(xml_path: pathlib.Path) -> str:
    root = ET.parse(xml_path).getroot()
    functions = []
    for function in root.findall(".//FinancialFunction"):
        abbreviation = text(function.find("Abbreviation"))
        name = abbreviation.lower()
        camel_case_name = text(function.find("CamelCaseName"))
        summary = text(function.find("ShortDescription"))
        group = group_variant(text(function.find("GroupId")))
        flags = [flag_variant(text(flag)) for flag in function.findall("./Flags/Flag")]
        required = [
            normalize_input_name(text(arg.find("Name")))
            for arg in function.findall("./RequiredInputArguments/RequiredInputArgument")
        ]
        optional = [
            normalize_optional_name(text(arg.find("Name")))
            for arg in function.findall("./OptionalInputArguments/OptionalInputArgument")
        ]
        output_count = len(function.findall("./OutputArguments/OutputArgument"))
        functions.append(
            {
                "name": name,
                "abbreviation": abbreviation,
                "camel_case_name": camel_case_name,
                "summary": summary,
                "signature": f"{name}({', '.join(required + optional)})",
                "group": group,
                "required_input_count": len(required),
                "optional_input_count": len(optional),
                "output_count": output_count,
                "flags": flags,
            }
        )

    functions.sort(key=lambda item: item["name"])
    lines = [
        "// @generated by tools/sync_talib_metadata.py",
        "// Do not edit manually.",
        "",
        "use super::{TalibFlag, TalibFunctionMetadata, TalibGroup};",
        "",
        "pub(super) const GENERATED_TALIB_METADATA: &[TalibFunctionMetadata] = &[",
    ]
    for function in functions:
        flags = (
            "&[]"
            if not function["flags"]
            else "&[" + ", ".join(f"TalibFlag::{flag}" for flag in function["flags"]) + "]"
        )
        lines.extend(
            [
                "    TalibFunctionMetadata {",
                f'        name: "{escape(function["name"])}",',
                f'        abbreviation: "{escape(function["abbreviation"])}",',
                f'        camel_case_name: "{escape(function["camel_case_name"])}",',
                f'        signature: "{escape(function["signature"])}",',
                f'        summary: "{escape(function["summary"])}",',
                f'        group: TalibGroup::{function["group"]},',
                f'        required_input_count: {function["required_input_count"]},',
                f'        optional_input_count: {function["optional_input_count"]},',
                f'        output_count: {function["output_count"]},',
                f"        flags: {flags},",
                "    },",
            ]
        )
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def text(node: ET.Element | None) -> str:
    return "" if node is None or node.text is None else node.text.strip()


def escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def group_variant(group: str) -> str:
    return {
        "Overlap Studies": "OverlapStudies",
        "Momentum Indicators": "MomentumIndicators",
        "Volume Indicators": "VolumeIndicators",
        "Volatility Indicators": "VolatilityIndicators",
        "Price Transform": "PriceTransform",
        "Cycle Indicators": "CycleIndicators",
        "Statistic Functions": "StatisticFunctions",
        "Math Transform": "MathTransform",
        "Math Operators": "MathOperators",
        "Pattern Recognition": "PatternRecognition",
    }[group]


def flag_variant(flag: str) -> str:
    return {
        "Overlap": "Overlap",
        "Unstable Period": "UnstablePeriod",
        "Candlestick": "Candlestick",
    }[flag]


def normalize_input_name(name: str) -> str:
    if name.startswith("in") and len(name) > 2 and name[2].isupper():
        name = name[2:]
    return to_snake_case(name)


def normalize_optional_name(name: str) -> str:
    return to_snake_case(name.replace("%", " percent "))


def to_snake_case(value: str) -> str:
    chars: list[str] = []
    prev_lower = False
    for char in value:
        if char.isalnum():
            if char.isupper() and prev_lower:
                chars.append("_")
            chars.append(char.lower())
            prev_lower = char.islower() or char.isdigit()
        else:
            if chars and chars[-1] != "_":
                chars.append("_")
            prev_lower = False
    result = "".join(chars).strip("_")
    while "__" in result:
        result = result.replace("__", "_")
    return result


if __name__ == "__main__":
    main()
